version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run main.go -b 0.0.0.0
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres_container
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pharmacy
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d pharmacy -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-db:

  